"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "../components/SideBar";
import Providers from "@/components/Provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useRouter } from "next/router";
import { usePathname } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const noLayoutPaths = ["/login"];

  const isNoLayout = noLayoutPaths.includes(pathname);

  if (isNoLayout) {
    return (
      <html lang="en">
        <body className={" bg-third font-['Poppins']"}>
          <Providers>
            <ToastContainer />
            <div className="p-4 text-fourth ">{children}</div>
          </Providers>
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body className={" bg-third font-['Poppins']"}>
        <Providers>
          <ToastContainer />
          <SideBar />
          <div className="p-4 text-fourth  sm:ml-64">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
